-- Schéma initial, conforme au diagramme D2 (docs/diagrammes/D2-modele-donnees.md).
-- SQL compatible PostgreSQL et H2 (mode PostgreSQL) : les tests tournent sans base locale.

CREATE TABLE promotion (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom  VARCHAR(100) NOT NULL,
    CONSTRAINT uk_promotion_nom UNIQUE (nom)
);

CREATE TABLE etudiant (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom           VARCHAR(100) NOT NULL,
    promotion_id  BIGINT NOT NULL,
    CONSTRAINT fk_etudiant_promotion FOREIGN KEY (promotion_id) REFERENCES promotion (id)
);
CREATE INDEX idx_etudiant_promotion ON etudiant (promotion_id);

-- RG1 : expiration_at = ouverture_at + 15 min. RG5 : code unique, jamais réutilisé.
-- RG21 : cloturee_at reste NULL tant que la session n'est pas clôturée.
CREATE TABLE session_cours (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre          VARCHAR(200) NOT NULL,
    promotion_id   BIGINT NOT NULL,
    code           VARCHAR(6) NOT NULL,
    ouverture_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    expiration_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    cloturee_at    TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_session_code UNIQUE (code),
    CONSTRAINT fk_session_promotion FOREIGN KEY (promotion_id) REFERENCES promotion (id)
);
CREATE INDEX idx_session_promotion ON session_cours (promotion_id);

-- RG4 : une présence par étudiant et par session. RG8 : source ETUDIANT ou FORMATEUR.
CREATE TABLE presence (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   BIGINT NOT NULL,
    etudiant_id  BIGINT NOT NULL,
    source       VARCHAR(10) NOT NULL,
    marquee_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_presence_session_etudiant UNIQUE (session_id, etudiant_id),
    CONSTRAINT ck_presence_source CHECK (source IN ('ETUDIANT', 'FORMATEUR')),
    CONSTRAINT fk_presence_session FOREIGN KEY (session_id) REFERENCES session_cours (id),
    CONSTRAINT fk_presence_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiant (id)
);
CREATE INDEX idx_presence_etudiant ON presence (etudiant_id);

-- RG10 : un exercice par étudiant et par session. Statuts : diagramme D4.
CREATE TABLE exercice (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   BIGINT NOT NULL,
    etudiant_id  BIGINT NOT NULL,
    lien         VARCHAR(500) NOT NULL,
    statut       VARCHAR(25) NOT NULL,
    depose_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    modifie_at   TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_exercice_session_etudiant UNIQUE (session_id, etudiant_id),
    CONSTRAINT ck_exercice_statut CHECK (statut IN ('DEPOSE', 'EN_ATTENTE_RELECTURE', 'EN_COURS_DE_RELECTURE', 'RELU')),
    CONSTRAINT fk_exercice_session FOREIGN KEY (session_id) REFERENCES session_cours (id),
    CONSTRAINT fk_exercice_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiant (id)
);
CREATE INDEX idx_exercice_etudiant ON exercice (etudiant_id);

-- Relation 1-1 avec l'exercice (Q6, RG13) : la relecture reprend l'id de son exercice.
-- RG3 : note entière de 0 à 20. RG18 : rendue_at posé une seule fois.
CREATE TABLE relecture (
    exercice_id   BIGINT PRIMARY KEY,
    relecteur_id  BIGINT NOT NULL,
    note          INTEGER,
    commentaire   VARCHAR(2000),
    assignee_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    commencee_at  TIMESTAMP WITH TIME ZONE,
    rendue_at     TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_relecture_note CHECK (note IS NULL OR note BETWEEN 0 AND 20),
    CONSTRAINT fk_relecture_exercice FOREIGN KEY (exercice_id) REFERENCES exercice (id),
    CONSTRAINT fk_relecture_relecteur FOREIGN KEY (relecteur_id) REFERENCES etudiant (id)
);
CREATE INDEX idx_relecture_relecteur ON relecture (relecteur_id);

-- RG7 : blocage de 2 minutes après 5 codes inconnus consécutifs.
CREATE TABLE blocage_code (
    etudiant_id         BIGINT PRIMARY KEY,
    echecs_consecutifs  INTEGER DEFAULT 0 NOT NULL,
    bloque_jusqua       TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_blocage_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiant (id)
);
