-- Étape 3, changement de besoin : chaque exercice est relu par deux pairs différents (RG13, remplace Q6).
-- Nouvelle migration : V1 n'est pas modifiée. Une base déjà remplie survit : toutes les relectures
-- existantes sont conservées, et les exercices déjà relus gardent leur relecture unique (RG26).
-- SQL compatible PostgreSQL et H2 (mode PostgreSQL).

-- 1. Nombre de relecteurs attendus par exercice : 2, sauf pour un exercice déjà relu sous l'ancienne règle.
ALTER TABLE exercice ADD COLUMN relecteurs_requis INTEGER DEFAULT 2 NOT NULL;
UPDATE exercice SET relecteurs_requis = 1 WHERE statut = 'RELU';
ALTER TABLE exercice ADD CONSTRAINT ck_exercice_relecteurs_requis CHECK (relecteurs_requis IN (1, 2));

-- 2. La relecture avait pour clé l'id de son exercice (relation 1-1). Elle reçoit son propre id :
--    nouvelle table, copie de toutes les lignes, puis remplacement de l'ancienne.
CREATE TABLE relecture_v2 (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercice_id   BIGINT NOT NULL,
    relecteur_id  BIGINT NOT NULL,
    note          INTEGER,
    commentaire   VARCHAR(2000),
    assignee_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    commencee_at  TIMESTAMP WITH TIME ZONE,
    rendue_at     TIMESTAMP WITH TIME ZONE
);

INSERT INTO relecture_v2 (exercice_id, relecteur_id, note, commentaire, assignee_at, commencee_at, rendue_at)
SELECT exercice_id, relecteur_id, note, commentaire, assignee_at, commencee_at, rendue_at
FROM relecture
ORDER BY assignee_at, exercice_id;

DROP TABLE relecture;
ALTER TABLE relecture_v2 RENAME TO relecture;

-- 3. Contraintes : RG3 (note 0-20), un pair ne relit pas deux fois le même exercice (RG14).
ALTER TABLE relecture ADD CONSTRAINT ck_relecture_note CHECK (note IS NULL OR note BETWEEN 0 AND 20);
ALTER TABLE relecture ADD CONSTRAINT uk_relecture_exercice_relecteur UNIQUE (exercice_id, relecteur_id);
ALTER TABLE relecture ADD CONSTRAINT fk_relecture_exercice FOREIGN KEY (exercice_id) REFERENCES exercice (id);
ALTER TABLE relecture ADD CONSTRAINT fk_relecture_relecteur FOREIGN KEY (relecteur_id) REFERENCES etudiant (id);
CREATE INDEX idx_relecture_relecteur ON relecture (relecteur_id);
